# Generated by Django 2.2 on 2021-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='employees')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentages', models.IntegerField()),
                ('days', models.IntegerField()),
                ('min_amount', models.FloatField()),
                ('max_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LastTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('d', 'deposit'), ('w', 'withdrawal')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=200)),
                ('company_number', models.CharField(max_length=15)),
                ('company_start_time', models.CharField(max_length=50)),
                ('amount_invested', models.IntegerField()),
                ('amount_paidout', models.IntegerField()),
                ('investors', models.IntegerField()),
                ('amount_invested_last', models.IntegerField()),
                ('amount_paidout_last', models.IntegerField()),
            ],
        ),
    ]
