# Generated by Django 2.2 on 2021-04-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='site_wallet_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
